[package]
name = "study_time"
version = "0.2.0"
authors = ["greembow <greembow@outlook.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["derive"] }
clap-verbosity-flag = "0.4.1"
env_logger = "0.9.0"
log = "0.4.14"
timer = "0.2.0"
